In [48]:
pip install opencv-python

Note: you may need to restart the kernel to use updated packages.


In [1]:
import cv2
import numpy as np

In [2]:
print(cv2.__version__)

4.6.0


In [24]:
src=cv2.imread('sca.png',cv2.IMREAD_COLOR)

In [25]:
print(type(src))

<class 'numpy.ndarray'>


In [26]:
src.shape

(470, 746, 3)

In [27]:
src.ndim

3

In [31]:
dst = cv2.blur(src, ksize=(9, 9), anchor=(-1, -1), borderType=cv2.BORDER_DEFAULT)

In [32]:
cv2.imshow("titan", dst)
cv2.waitKey()
cv2.destroyAllWindows()

In [23]:
b, g, r = cv2.split(src)

inverse = cv2.merge((r, g, b))

cv2.imshow("b", b)
cv2.imshow("g", g)
cv2.imshow("r", r)
cv2.imshow("inverse", inverse)
cv2.waitKey()
cv2.destroyAllWindows()

In [22]:
b.shape

(460, 690)

In [17]:
g

array([[  0,   2,   0, ...,   0,   1,   0],
       [  3, 255, 253, ..., 255, 255,   0],
       [  0, 250, 255, ..., 255, 255,   0],
       ...,
       [  0,  61,  64, ...,  88,  86,   0],
       [  0,  63,  64, ...,  90,  84,   0],
       [  0,   1,   1, ...,   0,   0,   0]], dtype=uint8)

In [18]:
r

array([[  0,   1,   1, ...,   0,   0,   0],
       [  1, 252, 249, ..., 255, 254,   0],
       [  1, 247, 255, ..., 255, 254,   0],
       ...,
       [  3, 126, 118, ...,  53,  50,   0],
       [  0, 120, 121, ...,  61,  50,   0],
       [  2,   0,   1, ...,   1,   0,   1]], dtype=uint8)

In [20]:
src

array([[[ 12,   0,   0],
        [  0,   2,   1],
        [  0,   0,   1],
        ...,
        [  2,   0,   0],
        [  0,   1,   0],
        [  2,   0,   0]],

       [[  0,   3,   1],
        [219, 255, 252],
        [216, 253, 249],
        ...,
        [245, 255, 255],
        [249, 255, 254],
        [  0,   0,   0]],

       [[  0,   0,   1],
        [219, 250, 247],
        [222, 255, 255],
        ...,
        [243, 255, 255],
        [245, 255, 254],
        [  0,   0,   0]],

       ...,

       [[  0,   0,   3],
        [ 81,  61, 126],
        [ 80,  64, 118],
        ...,
        [107,  88,  53],
        [100,  86,  50],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [ 82,  63, 120],
        [ 81,  64, 121],
        ...,
        [ 98,  90,  61],
        [ 96,  84,  50],
        [  0,   0,   0]],

       [[  1,   0,   2],
        [  0,   1,   0],
        [  1,   1,   1],
        ...,
        [  0,   0,   1],
        [  0,   0,   0],
        [  0,   0,   1]]