In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('C:\\Users\\zzuge\\OneDrive\\문서\\integrated1.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13527250 entries, 0 to 13527249
Data columns (total 37 columns):
 #   Column                               Dtype  
---  ------                               -----  
 0   Unnamed: 0                           int64  
 1   application_id                       int64  
 2   bank_id                              int64  
 3   product_id                           int64  
 4   loan_limit                           float64
 5   loan_rate                            float64
 6   is_applied                           float64
 7   application_n                        int64  
 8   weekday                              int64  
 9   user_id                              int64  
 10  gender                               float64
 11  insert_time                          float64
 12  credit_score                         float64
 13  yearly_income                        float64
 14  income_type                          object 
 15  company_enter_month           

In [4]:
df.isnull().sum()

Unnamed: 0                                    0
application_id                                0
bank_id                                       0
product_id                                    0
loan_limit                                 7382
loan_rate                                  7382
is_applied                              3257239
application_n                                 0
weekday                                       0
user_id                                       0
gender                                   128096
insert_time                                   0
credit_score                            1509276
yearly_income                                 6
income_type                                   0
company_enter_month                      400337
employment_type                               0
houseown_type                                 0
desired_amount                                0
purpose                                       0
personal_rehabilitation_yn              

In [3]:
#라벨인코딩을 하기 위함 dictionary map 생성 함수
def make_label_map(dataframe):
    label_maps = {}
    for col in dataframe.columns:
        if dataframe[col].dtype=='object':
            label_map = {'unknown':0}
            for i, key in enumerate(dataframe[col].unique()):
                label_map[key] = i  #새로 등장하는 유니크 값들에 대해 1부터 1씩 증가시켜 키값을 부여해줍니다.
            label_maps[col] = label_map
    return label_maps

# 각 범주형 변수에 인코딩 값을 부여하는 함수
def label_encoder(dataframe, label_map):
    for col in dataframe.columns:
        if dataframe[col].dtype=='object':
            dataframe[col] = dataframe[col].map(label_map[col])
            #dataframe[col] = dataframe[col].fillna(label_map[col]['unknown']) #혹시 모를 결측값은 unknown의 값(0)으로 채워줍니다.
    return dataframe

df = label_encoder(df, make_label_map(df))

In [4]:
df['personal_rehabilitation_complete_yn']=df['personal_rehabilitation_complete_yn'].fillna(0)
df['personal_rehabilitation_yn'] = df['personal_rehabilitation_yn'].fillna(0)

In [5]:
test=df[df['is_applied'].isnull()]

In [6]:
test

Unnamed: 0  application_id  bank_id  product_id  loan_limit  \
0                  0         1748340        7         191  42000000.0   
1                  1         1748340       25         169  24000000.0   
2                  2         1748340        2           7  24000000.0   
3                  3         1748340        4         268  29000000.0   
4                  4         1748340       11         118   5000000.0   
...              ...             ...      ...         ...         ...   
13527245    13527245         1513515       24         263   5000000.0   
13527246    13527246         1513515       55          24  19000000.0   
13527247    13527247         1513515       15         204  16000000.0   
13527248    13527248         1513515       30          85  10000000.0   
13527249    13527249         1513515       21          30  10000000.0   

          loan_rate  is_applied  application_n  weekday  user_id  ...  Login  \
0              13.6         NaN             35        1   430982  ...    0.0   
1              17.9         NaN             35        1   430982  ...    0.0   
2              18.5         NaN             35        1   430982  ...    0.0   
3              10.8         NaN             35        1   430982  ...    0.0   
4              16.4         NaN             35        1   430982  ...    0.0   
...             ...         ...            ...      ...      ...  ...    ...   
13527245       15.4         NaN             14        4    31658  ...    0.0   
13527246       11.5         NaN             14        4    31658  ...    0.0   
13527247       14.3         NaN             14        4    31658  ...    0.0   
13527248       14.3         NaN             14        4    31658  ...    0.0   
13527249       12.9         NaN             14        4    31658  ...    0.0   

          ViewLoanApplyIntro  StartLoanApply  CompleteIDCertification  \
0                       16.0            50.0                     15.0   
1                       16.0            50.0                     15.0   
2                       16.0            50.0                     15.0   
3                       16.0            50.0                     15.0   
4                       16.0            50.0                     15.0   
...                      ...             ...                      ...   
13527245                 1.0             1.0                      1.0   
13527246                 1.0             1.0                      1.0   
13527247                 1.0             1.0                      1.0   
13527248                 1.0             1.0                      1.0   
13527249                 1.0             1.0                      1.0   

          EndLoanApply  UseLoanManage  UsePrepayCalc  UseDSRCalc  \
0                 50.0            1.0            0.0         0.0   
1                 50.0            1.0            0.0         0.0   
2                 50.0            1.0            0.0         0.0   
3                 50.0            1.0            0.0         0.0   
4                 50.0            1.0            0.0         0.0   
...                ...            ...            ...         ...   
13527245           1.0            0.0            0.0         0.0   
13527246           1.0            0.0            0.0         0.0   
13527247           1.0            0.0            0.0         0.0   
13527248           1.0            0.0            0.0         0.0   
13527249           1.0            0.0            0.0         0.0   

          GetCreditInfo  loyalty  
0                   2.0        9  
1                   2.0        9  
2                   2.0        9  
3                   2.0        9  
4                   2.0        9  
...                 ...      ...  
13527245            0.0        0  
13527246            0.0        0  
13527247            0.0        0  
13527248            0.0        0  
13527249            0.0        0  

[3257239 rows x 37 columns]

In [9]:
test.isnull().sum()

Unnamed: 0                                   0
application_id                               0
bank_id                                      0
product_id                                   0
loan_limit                                1757
loan_rate                                 1757
is_applied                             3257239
application_n                                0
weekday                                      0
user_id                                      0
gender                                   36470
insert_time                                  0
credit_score                            265464
yearly_income                                6
income_type                                  0
company_enter_month                      96769
employment_type                              0
houseown_type                                0
desired_amount                               0
purpose                                      0
personal_rehabilitation_yn                   0
personal_reha

In [7]:
train=test[~((test['loan_limit'].isnull()) | (test['loan_rate'].isnull()) | (test['gender'].isnull()) | (test['credit_score'].isnull()) | (test['company_enter_month'].isnull()) | (test['existing_loan_cnt'].isnull()) | (test['existing_loan_amt'].isnull()) | (test['age'].isnull()))]

In [8]:
test1=test[(test['loan_limit'].isnull()) | (test['loan_rate'].isnull()) | (test['gender'].isnull()) | (test['credit_score'].isnull()) | (test['company_enter_month'].isnull()) | (test['existing_loan_cnt'].isnull()) | (test['existing_loan_amt'].isnull()) | (test['age'].isnull())]

In [12]:
train

Unnamed: 0  application_id  bank_id  product_id  loan_limit  \
0                  0         1748340        7         191  42000000.0   
1                  1         1748340       25         169  24000000.0   
2                  2         1748340        2           7  24000000.0   
3                  3         1748340        4         268  29000000.0   
4                  4         1748340       11         118   5000000.0   
...              ...             ...      ...         ...         ...   
13527231    13527231         1125770       34         243  30000000.0   
13527232    13527232         1125770       30          86  19000000.0   
13527233    13527233         1125770       55          24   4000000.0   
13527234    13527234         1125770       29         265   3000000.0   
13527235    13527235         1125770       42         216  10000000.0   

          loan_rate  is_applied  application_n  weekday  user_id  ...  Login  \
0              13.6         NaN             35        1   430982  ...    0.0   
1              17.9         NaN             35        1   430982  ...    0.0   
2              18.5         NaN             35        1   430982  ...    0.0   
3              10.8         NaN             35        1   430982  ...    0.0   
4              16.4         NaN             35        1   430982  ...    0.0   
...             ...         ...            ...      ...      ...  ...    ...   
13527231       17.9         NaN              6        4   876482  ...    0.0   
13527232       17.2         NaN              6        4   876482  ...    0.0   
13527233       13.0         NaN              6        4   876482  ...    0.0   
13527234       13.3         NaN              6        4   876482  ...    0.0   
13527235       14.6         NaN              6        4   876482  ...    0.0   

          ViewLoanApplyIntro  StartLoanApply  CompleteIDCertification  \
0                       16.0            50.0                     15.0   
1                       16.0            50.0                     15.0   
2                       16.0            50.0                     15.0   
3                       16.0            50.0                     15.0   
4                       16.0            50.0                     15.0   
...                      ...             ...                      ...   
13527231                 2.0             1.0                      1.0   
13527232                 2.0             1.0                      1.0   
13527233                 2.0             1.0                      1.0   
13527234                 2.0             1.0                      1.0   
13527235                 2.0             1.0                      1.0   

          EndLoanApply  UseLoanManage  UsePrepayCalc  UseDSRCalc  \
0                 50.0            1.0            0.0         0.0   
1                 50.0            1.0            0.0         0.0   
2                 50.0            1.0            0.0         0.0   
3                 50.0            1.0            0.0         0.0   
4                 50.0            1.0            0.0         0.0   
...                ...            ...            ...         ...   
13527231           1.0            3.0            0.0         0.0   
13527232           1.0            3.0            0.0         0.0   
13527233           1.0            3.0            0.0         0.0   
13527234           1.0            3.0            0.0         0.0   
13527235           1.0            3.0            0.0         0.0   

          GetCreditInfo  loyalty  
0                   2.0        9  
1                   2.0        9  
2                   2.0        9  
3                   2.0        9  
4                   2.0        9  
...                 ...      ...  
13527231            1.0        0  
13527232            1.0        0  
13527233            1.0        0  
13527234            1.0        0  
13527235            1.0        0  

[2295265 rows x 37 columns]

In [13]:
train.isnull().sum()

Unnamed: 0                                   0
application_id                               0
bank_id                                      0
product_id                                   0
loan_limit                                   0
loan_rate                                    0
is_applied                             2295265
application_n                                0
weekday                                      0
user_id                                      0
gender                                       0
insert_time                                  0
credit_score                                 0
yearly_income                                0
income_type                                  0
company_enter_month                          0
employment_type                              0
houseown_type                                0
desired_amount                               0
purpose                                      0
personal_rehabilitation_yn                   0
personal_reha

In [14]:
test1

Unnamed: 0  application_id  bank_id  product_id  loan_limit  \
508              508          728546       19         231  50000000.0   
509              509          728546       55          25  23000000.0   
510              510          728546       35          29   5000000.0   
511              511          728546       61          92  26000000.0   
512              512          728546       14         128  10000000.0   
...              ...             ...      ...         ...         ...   
13527245    13527245         1513515       24         263   5000000.0   
13527246    13527246         1513515       55          24  19000000.0   
13527247    13527247         1513515       15         204  16000000.0   
13527248    13527248         1513515       30          85  10000000.0   
13527249    13527249         1513515       21          30  10000000.0   

          loan_rate  is_applied  application_n  weekday  user_id  ...  Login  \
508            14.5         NaN             14        1     3058  ...    3.0   
509            13.9         NaN             14        1     3058  ...    3.0   
510            10.6         NaN             14        1     3058  ...    3.0   
511            12.8         NaN             14        1     3058  ...    3.0   
512            10.9         NaN             14        1     3058  ...    3.0   
...             ...         ...            ...      ...      ...  ...    ...   
13527245       15.4         NaN             14        4    31658  ...    0.0   
13527246       11.5         NaN             14        4    31658  ...    0.0   
13527247       14.3         NaN             14        4    31658  ...    0.0   
13527248       14.3         NaN             14        4    31658  ...    0.0   
13527249       12.9         NaN             14        4    31658  ...    0.0   

          ViewLoanApplyIntro  StartLoanApply  CompleteIDCertification  \
508                      4.0             1.0                      3.0   
509                      4.0             1.0                      3.0   
510                      4.0             1.0                      3.0   
511                      4.0             1.0                      3.0   
512                      4.0             1.0                      3.0   
...                      ...             ...                      ...   
13527245                 1.0             1.0                      1.0   
13527246                 1.0             1.0                      1.0   
13527247                 1.0             1.0                      1.0   
13527248                 1.0             1.0                      1.0   
13527249                 1.0             1.0                      1.0   

          EndLoanApply  UseLoanManage  UsePrepayCalc  UseDSRCalc  \
508                2.0            0.0            0.0         0.0   
509                2.0            0.0            0.0         0.0   
510                2.0            0.0            0.0         0.0   
511                2.0            0.0            0.0         0.0   
512                2.0            0.0            0.0         0.0   
...                ...            ...            ...         ...   
13527245           1.0            0.0            0.0         0.0   
13527246           1.0            0.0            0.0         0.0   
13527247           1.0            0.0            0.0         0.0   
13527248           1.0            0.0            0.0         0.0   
13527249           1.0            0.0            0.0         0.0   

          GetCreditInfo  loyalty  
508                 2.0        0  
509                 2.0        0  
510                 2.0        0  
511                 2.0        0  
512                 2.0        0  
...                 ...      ...  
13527245            0.0        0  
13527246            0.0        0  
13527247            0.0        0  
13527248            0.0        0  
13527249            0.0        0  

[961974 rows x 37 columns]

In [15]:
test1.isnull().sum()

Unnamed: 0                                  0
application_id                              0
bank_id                                     0
product_id                                  0
loan_limit                               1757
loan_rate                                1757
is_applied                             961974
application_n                               0
weekday                                     0
user_id                                     0
gender                                  36470
insert_time                                 0
credit_score                           265464
yearly_income                               6
income_type                                 0
company_enter_month                     96769
employment_type                             0
houseown_type                               0
desired_amount                              0
purpose                                     0
personal_rehabilitation_yn                  0
personal_rehabilitation_complete_y

In [9]:
train=train.drop(['SignUp','OpenApp','Login','ViewLoanApplyIntro','StartLoanApply','CompleteIDCertification','EndLoanApply','UseLoanManage','UsePrepayCalc','UseDSRCalc','GetCreditInfo'],axis=1)     

In [10]:
test1=test1.drop(['SignUp','OpenApp','Login','ViewLoanApplyIntro','StartLoanApply','CompleteIDCertification','EndLoanApply','UseLoanManage','UsePrepayCalc','UseDSRCalc','GetCreditInfo'],axis=1)     

In [11]:
import xgboost
from xgboost import XGBClassifier, XGBRegressor
from sklearn.model_selection import train_test_split

In [12]:
test1[test1['loan_rate'].isnull()].drop('loan_rate',axis=1)

Unnamed: 0  application_id  bank_id  product_id  loan_limit  \
3709            3709         1029177       51          21         NaN   
9950            9950          335684       42         249         NaN   
29193          29193         1592999       51          21         NaN   
29460          29460         1086409       13         262         NaN   
36617          36617         1288107        1         102         NaN   
...              ...             ...      ...         ...         ...   
13435883    13435883         1183404        1         130         NaN   
13442523    13442523          126250        1         102         NaN   
13511675    13511675         1685926       30          85         NaN   
13521234    13521234          938479        1         201         NaN   
13523274    13523274         1994208       42         249         NaN   

          is_applied  application_n  weekday  user_id  gender  ...  \
3709             NaN              9        1   787153     1.0  ...   
9950             NaN              8        4   759719     0.0  ...   
29193            NaN             22        4   300069     1.0  ...   
29460            NaN              4        1   477856     1.0  ...   
36617            NaN              8        3   381699     1.0  ...   
...              ...            ...      ...      ...     ...  ...   
13435883         NaN              8        4   402765     1.0  ...   
13442523         NaN             52        4   612096     0.0  ...   
13511675         NaN              7        4   111571     1.0  ...   
13521234         NaN             12        4   758120     1.0  ...   
13523274         NaN             17        4   268098     1.0  ...   

          employment_type  houseown_type  desired_amount  purpose  \
3709                    3              1       5000000.0        1   
9950                    0              1      50000000.0        1   
29193                   0              2      35000000.0        1   
29460                   0              2       5000000.0        1   
36617                   0              0      42000000.0        1   
...                   ...            ...             ...      ...   
13435883                0              2      30000000.0        1   
13442523                0              2      20000000.0        2   
13511675                3              1       5000000.0        1   
13521234                0              0      20000000.0        5   
13523274                0              1      15000000.0        4   

          personal_rehabilitation_yn  personal_rehabilitation_complete_yn  \
3709                             0.0                                  0.0   
9950                             0.0                                  0.0   
29193                            0.0                                  0.0   
29460                            0.0                                  0.0   
36617                            0.0                                  0.0   
...                              ...                                  ...   
13435883                         0.0                                  0.0   
13442523                         0.0                                  0.0   
13511675                         0.0                                  0.0   
13521234                         0.0                                  0.0   
13523274                         0.0                                  0.0   

          existing_loan_cnt  existing_loan_amt   age  loyalty  
3709                    5.0         12000000.0  45.0        1  
9950                    7.0         58000000.0  51.0        0  
29193                   6.0        126000000.0  49.0        1  
29460                   5.0         58000000.0  30.0        2  
36617                   8.0        142000000.0  48.0        4  
...                     ...                ...   ...      ...  
13435883                NaN                NaN  32.0        0  
13442523                2.

In [18]:
# loan_rate

x_test = test1[test1['loan_rate'].isnull()].drop(['loan_rate','loan_limit'],axis=1)

X_train = train.drop(['loan_rate','loan_limit'], axis = 1)
y_train = train['loan_rate']

xgb=XGBRegressor()
xgb.fit(X_train,y_train)
y_pred = xgb.predict(x_test)
y_pred

array([14.853469, 14.187947, 14.017942, ..., 17.960361, 14.044279,
       10.709117], dtype=float32)

In [19]:
# loan_limit

x_test = test1[test1['loan_limit'].isnull()].drop(['loan_rate','loan_limit'],axis=1)

X_train = train.drop(['loan_rate','loan_limit'], axis = 1)
y_train = train['loan_limit']

xgb=XGBRegressor()
xgb.fit(X_train,y_train)
y_pred = xgb.predict(x_test)
y_pred

array([14242784.,  4452831., 16751188., ..., 11363717., 21257276.,
       14468674.], dtype=float32)

In [20]:
# gender

x_test = test1[test1['gender'].isnull()].drop('gender',axis=1)

X_train = train.drop('gender', axis = 1)
y_train = train['gender']

xgb=XGBClassifier()
xgb.fit(X_train,y_train)
y_pred = xgb.predict(x_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [21]:
# credit_score

x_test = test1[test1['credit_score'].isnull()].drop('credit_score',axis=1)

X_train = train.drop('credit_score', axis = 1)
y_train = train['credit_score']

xgb=XGBRegressor()
xgb.fit(X_train,y_train)
y_pred = xgb.predict(x_test)
y_pred

array([837.9236 , 878.5475 , 868.2682 , ..., 890.92993, 832.3062 ,
       850.2442 ], dtype=float32)

In [17]:
train['company_enter_month']

0           20220201.0
1           20220201.0
2           20220201.0
3           20220201.0
4           20220201.0
               ...    
13527231    20220401.0
13527232    20220401.0
13527233    20220401.0
13527234    20220401.0
13527235    20220401.0
Name: company_enter_month, Length: 2295265, dtype: float64

In [22]:
# existing_loan_cnt

x_test = test1[test1['existing_loan_cnt'].isnull()].drop('existing_loan_cnt',axis=1)

X_train = train.drop('existing_loan_cnt', axis = 1)
y_train = train['existing_loan_cnt']

xgb=XGBRegressor()
xgb.fit(X_train,y_train)
y_pred = xgb.predict(x_test)
y_pred

array([ 3.5313008,  3.6127727,  3.449286 , ..., -1.357906 , -1.0986621,
       -0.8141797], dtype=float32)

In [23]:
# existing_loan_amt

x_test = test1[test1['existing_loan_amt'].isnull()].drop('existing_loan_amt',axis=1)

X_train = train.drop('existing_loan_amt', axis = 1)
y_train = train['existing_loan_amt']

xgb=XGBRegressor()
xgb.fit(X_train,y_train)
y_pred = xgb.predict(x_test)
y_pred

array([13669375., 15915078., 16423992., ..., 72634928., 70228760.,
       68856032.], dtype=float32)

In [28]:
# age

x_test = test1[test1['age'].isnull()].drop('age',axis=1)

X_train = train.drop('age', axis = 1)
y_train = train['age']

xgb=XGBRegressor()
xgb.fit(X_train,y_train)
y_pred = xgb.predict(x_test)
y_pred

array([39.297348, 38.681866, 38.398087, ..., 41.35498 , 41.52534 ,
       42.462734], dtype=float32)